# The public documentation URL, used for sitemap.xml
url: "https://docs.telerik.com/fiddler"

# Exclude files which should not be in the output
exclude: [README.md, Gemfile, Gemfile.lock, api_sort.rb]
navigation:
## List your directory names and order here, like this:
    Configure-Fiddler:
        title: Configure Fiddler
        position: 0
    Observe-Traffic:
        title: Observe Traffic
        position: 1
    Modify-Traffic:
        title: Modify Traffic
        position: 2
    Generate-Traffic:
        title: Generate Traffic
        position: 3
    Save-And-Load-Traffic:
        title: Save-And-Load Traffic
        position: 4
    Extend-Fiddler:
        title: Extend Fiddler
        position: 5
    "knowledge-base":
        title: "Knowledge Base"
        isNew: true
        position: 6
    Troubleshoot-Fiddler:
        title: Troubleshoot Fiddler
        position: 7

## Product title
product: "Progress Telerik Fiddler"

## The application virtual path
baseurl: /fiddler

## Assign layout and category per different paths
defaults:
-
    scope:
        path: ""
    values:
        layout: "page"
        category: "default"
        product: "fiddler"
        editable: true
-
    scope:
        path: "knowledge-base"
    values:
        layout: "kb-page"

## The Kendo UI version used
cdnVersion: "2017.3.1026"

# Aliases available in the markdown template. The below will expand {{site.foo}} to Bar in the output
# "foo": "Bar"

ff-sheet-id: aa62b076-27a9-f0b8-f954-e963653a5a2d

# The google services configuration
google_tag_manager: 'GTM-6X92'
google_custom_search: '001595215763381649090:fpe1norq_ow'
google_custom_kb_search: '001595215763381649090:hkokowggd0w'

# Assets pipeline configuration
assets:
    cachebust: soft
    js_compressor: uglifier
    gzip: false

## Do not edit below this line
safe: false
markdown: MarkdownProcessor